### pandas

>Pandas is a power full PYTHON library for manipulation and analysis of data

>Its a open source library

>fast(built on top of numpy),flexible(different source ),productive library

In [25]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [26]:
import pandas as pd

In [27]:
pd.__version__

'2.2.3'

#### Series - One dimensional array (data structure)with label

In [28]:
l1=[1,2,3,4,5]
type(l1)

list

In [29]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
s=pd.Series(l1,index=["a","b","c","d","e"],name="My series")
s

a    1
b    2
c    3
d    4
e    5
Name: My series, dtype: int64

In [31]:
type(s)

pandas.core.series.Series

In [32]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [33]:
s.values

array([1, 2, 3, 4, 5])

note:Index does not support mutable operations

In [34]:
s.index[0]='z'

TypeError: Index does not support mutable operations

In [ ]:
# changing the index of pandas series
s.rename(index={'b':'y'},inplace=True)
s

a    1
y    2
c    3
d    4
e    5
Name: My series, dtype: int64

### DataFrame -Its a 2d array(just like tables)
> rows and cols

In [ ]:
dict={'Name':['virat','Rohit','Dhoni','Jadeja','Bumrah','Shami'],
      'Age':[39,40,38,35,45,30],
      'Marks':[90,92,91,93,94,96],
      'Role':['Bats man','batsman','wicket keeper','all rounder','bowler','bowler']}
df=pd.DataFrame(dict)
df

     Name  Age  Marks           Role
0   virat   39     90       Bats man
1   Rohit   40     92        batsman
2   Dhoni   38     91  wicket keeper
3  Jadeja   35     93    all rounder
4  Bumrah   45     94         bowler
5   Shami   30     96         bowler

In [ ]:

type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

     Name  Age  Marks           Role
0   virat   39     90       Bats man
1   Rohit   40     92        batsman
2   Dhoni   38     91  wicket keeper
3  Jadeja   35     93    all rounder
4  Bumrah   45     94         bowler

In [ ]:
df.tail(2)

     Name  Age  Marks    Role
4  Bumrah   45     94  bowler
5   Shami   30     96  bowler

In [ ]:
len(df)

6

In [ ]:
df.count()

Name     6
Age      6
Marks    6
Role     6
dtype: int64

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Role'], dtype='object')

In [ ]:
df['Name']

0     virat
1     Rohit
2     Dhoni
3    Jadeja
4    Bumrah
5     Shami
Name: Name, dtype: object

single column is defined as series

In [ ]:
type(df['Name'])

pandas.core.series.Series

set of rows and columns is defined as DataFrame

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df['Name'].value_counts()

Name
virat     1
Rohit     1
Dhoni     1
Jadeja    1
Bumrah    1
Shami     1
Name: count, dtype: int64

In [ ]:
dict1={'Name':['virat','virat','Dhoni','Jadeja','Bumrah','Shami'],
      'Age':[39,40,38,35,45,30],
      'Marks':[90,92,91,93,94,96],
      'Role':['Bats man','batsman','wicket keeper','all rounder','bowler','bowler']}
df=pd.DataFrame(dict1)
df

     Name  Age  Marks           Role
0   virat   39     90       Bats man
1   virat   40     92        batsman
2   Dhoni   38     91  wicket keeper
3  Jadeja   35     93    all rounder
4  Bumrah   45     94         bowler
5   Shami   30     96         bowler

In [ ]:
df['Name'].value_counts()
# here name virat is repeated two times.

Name
virat     2
Dhoni     1
Jadeja    1
Bumrah    1
Shami     1
Name: count, dtype: int64

#Day 03

#### Basic  operations:

> Importing dataset from different files

> Importing tabular dataset

In [ ]:
import pandas as pd

In [36]:
import pandas as pd

stock_df = pd.read_csv(r"C:\Users\klemp\Desktop\Data Analyst 61 G\dataset\ETH_1h.csv")

##### In ML coulumn name is call like feature,label,head

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

by default head() will return first/top five rows

In [ ]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

head(10) it will return first ten rows

In [ ]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

bottom five rows

In [ ]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

len is used to get number of rows

In [ ]:
len(stock_df)

23674

> Access column names of dataframe

>if we use() this parantesis it will become method other wise it is attribute

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [ ]:
#### Accessing a single column
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [ ]:
## for accessing  multiple column use array
stock_df[['Open','Symbol','High']]

         Open  Symbol    High
0      129.94  ETHUSD  131.82
1      119.51  ETHUSD  132.02
2      124.47  ETHUSD  124.85
3      124.08  ETHUSD  127.42
4      124.85  ETHUSD  129.51
...       ...     ...     ...
23669  265.74  ETHUSD  272.74
23670  268.79  ETHUSD  269.90
23671  274.83  ETHUSD  274.93
23672  275.01  ETHUSD  275.01
23673  279.98  ETHUSD  279.99

[23674 rows x 3 columns]

#Accessing rows using loc and iloc 

>if we using iloc it is for index location

>loc is for if index is in name

>loc is label location

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

apart from int and float other datatype is object

In [ ]:
stock_df.iloc[0]

Date      2020-03-13 08-PM
Symbol              ETHUSD
Open                129.94
High                131.82
Low                 126.87
Close               128.71
Volume          1940673.93
Name: 0, dtype: object

In [ ]:
stock_df.head(2)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09

In [ ]:
stock_df.loc[0:10,['Date', 'Symbol', 'Open', 'High']]

                Date  Symbol    Open    High
0   2020-03-13 08-PM  ETHUSD  129.94  131.82
1   2020-03-13 07-PM  ETHUSD  119.51  132.02
2   2020-03-13 06-PM  ETHUSD  124.47  124.85
3   2020-03-13 05-PM  ETHUSD  124.08  127.42
4   2020-03-13 04-PM  ETHUSD  124.85  129.51
5   2020-03-13 03-PM  ETHUSD  128.39  128.90
6   2020-03-13 02-PM  ETHUSD  134.03  137.90
7   2020-03-13 01-PM  ETHUSD  131.35  140.95
8   2020-03-13 12-PM  ETHUSD  128.93  134.60
9   2020-03-13 11-AM  ETHUSD  132.60  133.17
10  2020-03-13 10-AM  ETHUSD  133.80  134.99

In [ ]:
stock_df.loc[10,['Date', 'Symbol', 'Open', 'High']]

Date      2020-03-13 10-AM
Symbol              ETHUSD
Open                 133.8
High                134.99
Name: 10, dtype: object

In [ ]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

if we working with normal 2d array in slicing [][] will happen like this 
> in np.array slicing is [ , ]

In [ ]:
d2=[[1,4,7],[2,4,6],[7,9,8]]
d2

[[1, 4, 7], [2, 4, 6], [7, 9, 8]]

In [ ]:
d2[0][1]

4

In [ ]:
import numpy as np

In [ ]:
d2=[[1,4,7],[2,4,6],[7,9,8]]
np.array=d2

In [ ]:
d2

[[1, 4, 7], [2, 4, 6], [7, 9, 8]]

In [ ]:
d2[0:2]

[[1, 4, 7], [2, 4, 6]]

slicing

In [ ]:
stock_df.loc[10,'Date': 'High'] # in number slicing last one is exclusive but in string both are inclusive

Date      2020-03-13 10-AM
Symbol              ETHUSD
Open                 133.8
High                134.99
Name: 10, dtype: object

##when the exact position is known but label name is unknown in that time we use iloc

iloc is the index based location

In [ ]:
stock_df.iloc[0]

Date      2020-03-13 08-PM
Symbol              ETHUSD
Open                129.94
High                131.82
Low                 126.87
Close               128.71
Volume          1940673.93
Name: 0, dtype: object

In [ ]:
df.iloc[2,0:7] #slicing of column index

Date      2020-03-13 06-PM
Symbol              ETHUSD
Open                124.47
High                124.85
Low                  115.5
Close               119.51
Volume          4898735.81
Name: 2, dtype: object

In [ ]:
stock_df.iloc[2,2]# row index and column index

np.float64(124.47)

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.3'

In [37]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [38]:
import numpy as np

print(type(np.array))
print(np.array)

<class 'builtin_function_or_method'>
<built-in function array>

In [39]:
stock_df.iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

In [43]:
f1=stock_df['High']>130
stock_df[f1]
stock_gt_130=stock_df[f1]

In [44]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [42]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

Adding a new column

In [45]:
stock_df['random_col']=list(range(1,len(stock_df)+1))

In [46]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

Droping the columns
here axis=1 is column and 0 is row

In [48]:
len(stock_df)

23674

In [49]:
stock_df['Random_col']=list(range(1,len(stock_df)+1))

In [50]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,random_col,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5,5
...,...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674,23674

In [51]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [52]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

In [59]:
stock_df.drop(columns=['Open','High'],inplace=True)

In [60]:
stock_df

                   Date  Symbol     Low   Close      Volume  random_col
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93           1
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92           4
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71           5
5      2020-03-13 03-PM  ETHUSD  116.06  124.85  7378976.00           6
6      2020-03-13 02-PM  ETHUSD  125.50  128.39  3733916.89           7
...                 ...     ...     ...     ...         ...         ...
23668  2017-07-01 04-PM  ETHUSD  267.60  268.00  1287300.75       23669
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55       23670
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85       23671
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99       23672
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87       23674

[23671 rows x 6 columns]

In [55]:
stock_df.drop(23672,axis=0,inplace=True)

In [56]:
len(stock_df)

23673

In [57]:
stock_df.drop([1,2],axis=0,inplace=True)

In [58]:
len(stock_df)

23671